version: '3.9'
services:
#  web:
#    image: almgergo/sg-game-fe
#    ports:
#      - "4200:80"
  backend:
    image: almgergo/sg-game-be
    ports:
      - '8080:8080'
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

